flags:
  texmath:
    network-uri: true
    executable: true
packages:
- '.'
extra-deps:
- git: https://github.com/jgm/pandoc-types.git
  commit: aed20ed845edf98110995217d66d4627a1824eea
resolver: lts-18.10
